project:
  namespace: "org.simplemodeling.textus"
  id: "AiRuntime"
  name: "textus-ai-runtime"
  scalaPackage: "org.simplemodeling.textus.airuntime"
  title: "Textus AI Runtime"
  kind: car
  component:
    name: "AiRuntime"
    className: "AiRuntimeComponent"
    displayName: "Textus AI Runtime"
    version: "0.2.2"
    config:
      textus.server.default-port: "18002"

cml:
  source: "src/main/cozy/ai.cml"

build:
  scalaVersion: "3.3.8"
  cozyVersion: "0.3.2.2"
  dependencies:
    compile:
      - "org.goldenport::goldenport-cncf:0.5.2"
      - "org.simplemodeling::simplemodeling-model:0.2.0"
    test:
      - "org.scalatest::scalatest:3.2.19"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    manifest_metadata:
      boundedContext: "platform"
      domain: "ai-runtime"
    runtime:
      cncf:
        minimum: "0.5.2"
        excluded: []
        tested:
          - "0.5.2"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-ai-runtime"
