project:
  name: "textus-ai-runtime"
  title: "Textus AI Runtime"
  kind: car
  organization: "org.textus"
  scalaPackage: "org.simplemodeling.textus.ai"
  component:
    name: "textus-ai-runtime"
    className: "TextusAi"
    displayName: "Textus AI Runtime"
    version: "0.2.1-SNAPSHOT"
    config:
      textus.server.default-port: "18001"

publication:
  source_manifest:
    enabled: false

packaging:
  kind: car
  car:
    runtime:
      cncf:
        minimum: "0.5.1-SNAPSHOT"
        excluded: []
        tested:
          - "0.5.1-SNAPSHOT"

warehouse:
  repository_artifacts:
    include:
      - car
    modules:
      - "textus-ai-runtime"
